name = "CFShallowWaters"
uuid = "27b57071-4f7a-481a-ba32-ffa10dd904ac"
authors = ["The ClimFlows contributors"]
version = "0.2.0"

[deps]
CFDomains = "3699aaca-035b-4155-96ec-eecb526248de"
CFPlanets = "9c2ca15e-caec-41c0-a22c-2e93fe5a241f"
CookBooks = "7bce7c31-0f61-4fd7-bdaf-6b04abfa2cc7"
ManagedLoops = "36a4119d-6b73-4371-88fe-ba2d91f5495d"
MemberFunctions = "5d9104bf-354e-4e91-8ca5-37bef64dfa22"
MutatingOrNot = "6a37069a-9a67-4b2d-a34a-f09ab4b23c7c"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"

[weakdeps]
CFTimeSchemes = "79282218-dfaf-41aa-91df-a06f65ece871"

[extensions]
CFTimeSchemes_Ext = ["CFTimeSchemes"]

[compat]
CFDomains = "0.3.14"
CFPlanets = "0.1"
CFTimeSchemes = "0.3"
CookBooks = "0.2"
ManagedLoops = "0.1.3"
MemberFunctions = "0.1"
MutatingOrNot = "0.1.5"
PackageExtensionCompat = "1.0"
julia = "1.8"

[extras]
CFTimeSchemes = "79282218-dfaf-41aa-91df-a06f65ece871"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
